name: mac-xcodebuild-actions-workflow
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: TestProject.xcodeproj
          scheme: TestProject
          destination: platform=iOS
          action: test
