name: mac-xcodebuild-actions-workflow
on: push
jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0'
        
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: TestProject.xcodeproj
          scheme: TestProject
          destination: platform=iOS
          action: test
